* anerd, anerd-server-tcp.1 => anerd-server.1, anerd-server-tcp =>   anerd-server, anerd-server-tcp.go => anerd-server.go, anerd-server-   udp.1, anerd-server-udp.c, configure.ac, debian/anerd-   client.default, debian/anerd-server.anerd-server-tcp.upstart =>   debian/anerd-server.upstart, debian/anerd-server.anerd-server-   udp.upstart, debian/anerd-server.default, debian/anerd-   server.install, debian/anerd-server.manpages, debian/control,   debian/rules, Makefile.am:   - completely deprecate the UDP operation of both the client and     the server   - the TLS server over TCP is the only supported protocol going     forward   - this will necessitate a major version bump

diff --git a/anerd b/anerd
--- a/anerd
+++ b/anerd
@@ -24,7 +24,7 @@ error() {
 }
 
 log() {
-	printf "$(date '+%b %e %T') $(hostname) anerd[$$]: ${PROTO} $@\n" 1>&2
+	printf "$(date '+%b %e %T') $(hostname) anerd[$$]: $@\n" 1>&2
 }
 
 random_hash() {
@@ -52,23 +52,7 @@ salt_hash_and_write() {
 	log "client salted and hashed response from [${2}]"
 }
 
-udp_exchange() {
-	local cmd=""
-	case "${IPV6}" in
-		true|TRUE|1)
-			cmd="socat -v -t ${WAIT} UDP6-DATAGRAM:[${1}]:${2}"
-		;;
-		*)
-			cmd="socat -v -t ${WAIT} - UDP-DATAGRAM:${1}:${2}"
-		;;
-	esac
-	local f=$(mktemp -t "${PKG}.XXXXXXXXXXXX")
-	log "client sent hashed entropy to [${1}:${2}]"
-	(random_hash | $cmd >"${f}" 2>&1) || error "UDP network communication failed [$?]"
-	salt_hash_and_write "${f}" ${1}:${2}
-}
-
-tcp_exchange() {
+exchange() {
 	local f1=$(mktemp -t "${PKG}.XXXXXXXXXXXX")
 	local f2=$(mktemp -t "${PKG}.XXXXXXXXXXXX")
 	printf "tag=" > "${f1}"
@@ -80,29 +64,12 @@ tcp_exchange() {
 	local cmd="curl ${CURL_OPTS} -o- -v --trace-time --connect-timeout 3 --max-time 3 --data @${f1} --data @${f2} ${1}"
 	log "client sent hashed entropy to [${1}]"
 	local f=$(mktemp -t "${PKG}.XXXXXXXXXXXX")
-	($cmd >"${f}.out" 2>"${f}.err") || error "TCP network communication failed [$?]\n$(cat ${f})"
-	[ "${challenge_response}" = $(head -n1 "${f}.out") ] || error "TCP server failed challenge/response [expected=${challenge_response}] != [got=$(head -n1 ${f}.out)]"
+	($cmd >"${f}.out" 2>"${f}.err") || error "Network communication failed [$?]\n$(cat ${f})"
+	[ "${challenge_response}" = $(head -n1 "${f}.out") ] || error "Server failed challenge/response [expected=${challenge_response}] != [got=$(head -n1 ${f}.out)]"
 	log "client verified challenge/response with [${1}]"
 	salt_hash_and_write "${f}" ${1}
 }
 
-broadcast() {
-	local cmd="" dest=""
-	case "${IPV6}" in
-		true|TRUE|1)
-			dest="ff02::1"
-			cmd="socat -v -t ${WAIT} - UDP6-DATAGRAM:[${dest}]:${1}"
-		;;
-		*)
-			dest="255.255.255.255"
-			cmd="socat -v -t ${WAIT} - UDP-DATAGRAM:${dest}:${1},broadcast"
-		;;
-	esac
-	log "client sent hashed entropy to [${dest}:${1}]"
-	local f=$(mktemp -t "${PKG}.XXXXXXXXXXXX")
-	(random_hash | $cmd >"${f}" 2>&1) || error "UDP network communication failed [$?]"
-	salt_hash_and_write "${f}" ${dest}:${1}
-}
 # Source configuration
 PKG="anerd"
 [ -r "/etc/default/${PKG}-client" ] && . "/etc/default/${PKG}-client"
@@ -133,14 +100,6 @@ while [ ! -z "$1" ]; do
 			POOL="${POOL} $2"
 			shift 2
 		;;
-		-t|--tcp)
-			PROTO="tcp"
-			shift
-		;;
-		-u|--udp)
-			PROTO="udp"
-			shift
-		;;
 		-w|--wget-opts)
 			WGET_OPTS="$2"
 			shift 2
@@ -154,41 +113,9 @@ done
 [ -n "${IPV6}" ] || IPV6=false
 [ -n "${BYTES}" ] || BYTES=64
 [ -n "${WAIT}" ] || WAIT="0.1"
-[ -n "${PROTO}" ] || PROTO="tcp"
-if [ "${PROTO}" = "udp" ]; then
-	if [ -z "${POOL}" ]; then
-		POOL="${POOL_UDP}"
-		if [ -z "${POOL}" ]; then
-			error "No servers configured in pool"
-		fi
-	fi
-	command -v socat >/dev/null 2>&1 || error "You will need to install the suggested 'socat' package to use the udp client"
-	# Loop over servers configured in the pool
-	for i in ${POOL}; do
-		# Get the hostname/ip
-		h=${i%%:*}
-		# Get the port, or set to default
-		p=${i##*:}
-		[ "${h}" = "${p}" ] && p="26373"
-		[ -n "${h}" ] || continue
-		udp_exchange "${h}" "${p}"
-	done
-	if [ "${BROADCAST}" = "1" ]; then
-		# Now broadcast to the local network
-		broadcast 26373 || true
-	fi
-elif [ "${PROTO}" = "tcp" ]; then
-	if [ -z "${POOL}" ]; then
-		POOL="${POOL_TCP}"
-		if [ -z "${POOL}" ]; then
-			error "No servers configured in pool"
-		fi
-	fi
-	command -v curl >/dev/null 2>&1 || error "You will need to install the 'curl' package to use the udp client"
-	# Default is TCP
-	for i in ${POOL}; do
-		tcp_exchange "${i}"
-	done
-else
-	error "Invalid protocol"
+if [ -z "${POOL}" ]; then
+	error "No servers configured in pool"
 fi
+for i in ${POOL}; do
+	exchange "${i}"
+done
