- deprecate hash as a configurable; use sha512sum * anerd:   - use socat in verbose mode, to add more timestamps to the log   - hash the timestamped log output

diff --git a/anerd b/anerd
--- a/anerd
+++ b/anerd
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# anerd: a Network Exchange Randomness Daemon client wrapper
+# anerd: a Network Exchange Randomness Daemon client
 #
 #  Copyright (C) 2012-2013 Dustin Kirkland <dustin.kirkland@gmail.com>
 #
@@ -44,29 +44,29 @@ salt_hash_and_write() {
 	local bytes=$(wc -c "${1}" | awk '{print $1}')
 	cat "${1}" | salt | sha512sum > "${DEVICE}"
 	rm -f "${1}"
-	printf "$(date '+%b %e %T') $(hostname) anerd[$$]: ${PROTO} client recv from [${2}]\n" 1>&2
+	printf "$(date '+%b %e %T') $(hostname) anerd[$$]: ${PROTO} client hashed [${bytes} bytes] from [${2}]\n" 1>&2
 }
 
 udp_exchange_random_bytes() {
 	local cmd=""
 	case "${IPV6}" in
 		true|TRUE|1)
-			cmd="socat -t ${WAIT} UDP6-DATAGRAM:[${1}]:${2}"
+			cmd="socat -v -t ${WAIT} UDP6-DATAGRAM:[${1}]:${2}"
 		;;
 		*)
-			cmd="socat -t ${WAIT} - UDP-DATAGRAM:${1}:${2}"
+			cmd="socat -v -t ${WAIT} - UDP-DATAGRAM:${1}:${2}"
 		;;
 	esac
 	local f=$(mktemp -t "${PKG}.XXXXXXXXXXXX")
-	printf "$(date '+%b %e %T') $(hostname) anerd[$$]: ${PROTO} client sent to [${1}:${2}]\n" 1>&2
-	(random_bytes | $cmd > "${f}") || error "UDP network communication failed [$?]"
+	printf "$(date '+%b %e %T') $(hostname) anerd[$$]: ${PROTO} client sent [${BYTES} bytes] to [${1}:${2}]\n" 1>&2
+	(random_bytes | $cmd >"${f}" 2>&1) || error "UDP network communication failed [$?]"
 	salt_hash_and_write "${f}" ${1}:${2}
 }
 
 tcp_exchange_random_bytes() {
 	local url="${1}?r=$(cat /proc/sys/kernel/random/boot_id)__$(cat /proc/sys/kernel/random/uuid)"
 	local cmd="curl ${CURL_OPTS} -o- -v --trace-time ${url}"
-	printf "$(date '+%b %e %T') $(hostname) anerd[$$]: ${PROTO} client sent to [${1}]\n" 1>&2
+	printf "$(date '+%b %e %T') $(hostname) anerd[$$]: ${PROTO} client sent [16 bytes] to [${1}]\n" 1>&2
 	local f=$(mktemp -t "${PKG}.XXXXXXXXXXXX")
 	($cmd >"${f}" 2>&1) || error "TCP network communication failed [$?]\n$(cat ${f})"
 	salt_hash_and_write "${f}" ${1}
@@ -77,16 +77,16 @@ broadcast() {
 	case "${IPV6}" in
 		true|TRUE|1)
 			dest="ff02::1"
-			cmd="socat -t ${WAIT} - UDP6-DATAGRAM:[${dest}]:${1}"
+			cmd="socat -v -t ${WAIT} - UDP6-DATAGRAM:[${dest}]:${1}"
 		;;
 		*)
 			dest="255.255.255.255"
-			cmd="socat -t ${WAIT} - UDP-DATAGRAM:${dest}:${1},broadcast"
+			cmd="socat -v -t ${WAIT} - UDP-DATAGRAM:${dest}:${1},broadcast"
 		;;
 	esac
 	printf "$(date '+%b %e %T') $(hostname) anerd[$$]: ${PROTO} client sent to [${dest}:${1}]\n" 1>&2
 	local f=$(mktemp -t "${PKG}.XXXXXXXXXXXX")
-	(random_bytes | $cmd > "${f}") || error "UDP network communication failed [$?]"
+	(random_bytes | $cmd >"${f}" 2>&1) || error "UDP network communication failed [$?]"
 	salt_hash_and_write "${f}" ${dest}:${1}
 }
 # Source configuration
@@ -134,6 +134,12 @@ done
 [ -n "${WAIT}" ] || WAIT="0.1"
 [ -n "${PROTO}" ] || PROTO="tcp"
 if [ "${PROTO}" = "udp" ]; then
+	if [ -z "${POOL}" ]; then
+		POOL="${POOL_UDP}"
+		if [ -z "${POOL}" ]; then
+			error "No servers configured in pool"
+		fi
+	fi
 	# Loop over servers configured in the pool
 	for i in ${POOL}; do
 		# Get the hostname/ip
@@ -150,7 +156,10 @@ if [ "${PROTO}" = "udp" ]; then
 	fi
 elif [ "${PROTO}" = "tcp" ]; then
 	if [ -z "${POOL}" ]; then
-		error "No servers configured in pool"
+		POOL="${POOL_TCP}"
+		if [ -z "${POOL}" ]; then
+			error "No servers configured in pool"
+		fi
 	fi
 	# Default is TCP
 	for i in ${POOL}; do
