* pollinate:   - move CURL_OPTS to the end of the line, so that the admin can override     any curl option, such as the user-agent string in /etc/default/pollinate

diff --git a/pollinate b/pollinate
--- a/pollinate
+++ b/pollinate
@@ -97,7 +97,7 @@ exchange() {
 	local out="${TMPDIR}/out"
 	local err="${TMPDIR}/err"
 	user_agent
-	curl ${CURL_OPTS} -A "${USER_AGENT}" -o- -v --trace-time --connect-timeout ${WAIT} --max-time ${WAIT} --data @${f1} ${server} >"${out}" 2>"${err}" || error "Network communication failed [$?]\n$(cat ${out} ${err})"
+	curl -A "${USER_AGENT}" -o- -v --trace-time --connect-timeout ${WAIT} --max-time ${WAIT} --data @${f1} ${CURL_OPTS} ${server} >"${out}" 2>"${err}" || error "Network communication failed [$?]\n$(cat ${out} ${err})"
 	if [ "${NO_CHALLENGE}" != "1" ]; then
 		[ "${challenge_response}" = $(head -n1 "${out}") ] || error "Server failed challenge/response [expected=${challenge_response}] != [got=$(head -n1 ${out})]"
 		log "client verified challenge/response with [${server}]"
